MultiShop/MultiShop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, ProductSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
    'products': ProductSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    #path('robots.txt/', lambda request: render(request, 'robots.txt', content_type='text/plain')), | alttaki setirnen eyni islevi gorur.
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap')
] + i18n_patterns(
    path('', include('ecommerce.urls')),
    path('customer/', include('customer.urls'))
)

MultiShop/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('bascet/', views.bascet, name='bascet'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('confirm-contact/', views.confirm_contact, name='confirm-contact'),
    path('add-to-bascet/<int:pk>/', views.add_to_bascet, name = 'add-to-bascet'),
    path('update-bascet-quantity/<int:pk>/', views.update_bascet_quantity, name = 'update-bascet-quantity'),
    path('remove-bascet/<int:pk>/', views.remove_bascet, name='remove-bascet'),
    path('add-to-wish/<int:pk>/', views.add_to_wish, name = 'add-to-wish'),
    path('remove-wish/<int:pk>/', views.remove_wish, name='remove-wish'),
    path('change-currency/<str:currency>/', views.change_currency, name='change-currency'),
    path('reset-password<str:uuid>/<str:token>', views.reset_password, name='reset-password'),
    path('reset-password-email', views.reset_password_email, name='reset-password-email'),


]

MultiShop/ecommerce/urls.py
from django.urls import path
from . import views


app_name = 'ecommerce'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('detail/product/<int:pk>/<str:slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('review/<int:pk>/', views.review, name='review')
]

MultiShop/ecommerce/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.admin import display
from django.utils.html import format_html
from ckeditor.fields import RichTextField
from imagekit.models.fields import ProcessedImageField
from .utils import convert_slug
from django.db.models import Avg
from django.utils.translation import get_language
# Create your models here.



class Category(models.Model):
    supper = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=100, verbose_name='Kategorya Adi')
    image = models.ImageField(upload_to='category-images/', null=True)
    created = (models.DateTimeField(auto_now_add=True))
    
    class Meta:
        verbose_name = "Kategorya"
        verbose_name_plural = "Kategoryalar"

    def __str__(self):
        return self.title
    
    def is_super(self):
        return self.category_set.exists()
    
    def get_absolute_url(self):
        return reverse("ecommerce:product-list") + f'?category={self.pk}'
    
    
    
    @display(description='Kateqorya sekili')
    def category_image(self):
        return format_html(f'<img width=250 src="{self.image.url}">')
    
 
class Campaing(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    discount = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(100)], null=True, blank=True)
    image = models.ImageField(upload_to='campaing_images/')
    created = models.DateField(auto_now_add=True)
    slide = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("ecommerce:product-list") + f'?campaings={self.pk}'
    
    class Meta:
        verbose_name = "Kampanya"
        verbose_name_plural = "Kampanyalar"
        
        
    
class Size (models.Model):
    title = models.CharField(max_length=10)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Ölçü"
        verbose_name_plural = "Ölçülər"
    
class Color (models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = "Rəng"
        verbose_name_plural = "Rənglər"
        
class Product(models.Model):
    title_az = models.TextField(max_length=100, verbose_name='Başlıq')
    title_tr = models.TextField(max_length=100, null=True, blank=True, verbose_name='Başlık')
    title_en = models.TextField(max_length=100, null=True, blank=True, verbose_name='Title')
    slug = models.SlugField(null=True, blank=True)
    description = RichTextField(max_length=200, verbose_name='Məzmun')
    content = RichTextField(verbose_name='Haqqinda')
    old_price = models.FloatField(validators=[MinValueValidator(0.1)] , verbose_name='Kohne Qiymet')
    new_price = models.FloatField(validators=[MinValueValidator(0.1)] , verbose_name='Hazirki Qiymet')
    sizes = models.ManyToManyField(Size)
    colors = models.ManyToManyField(Color)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Kateqorya')
    cover = ProcessedImageField(upload_to='products/product-cover-images/', format='JPEG', options={'quality': 60}, verbose_name='Qapaq Sekili')
    campaings = models.ManyToManyField(Campaing, blank=True)
    featured = models.BooleanField(default=False)
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yerləşdirilmə Tarixi')
        
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Məhsul"
        verbose_name_plural = "Məhsullar"


    @display(description='Qapaq Sekili')
    def product_cover(self):
        return format_html(f'<img width=250 src="{self.cover.url}">')

    def get_absolute_url(self):
        return reverse("ecommerce:product-detail", kwargs={"pk": self.pk, "slug": self.slug})

 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = convert_slug(self.title)
        super().save(*args, **kwargs)

    @property
    def title(self):
        lang = get_language()
        title = getattr(self, 'title_' + lang)
        return title or self.title_az
    
    @property
    def average_star_count(self):
        reviews = self.review_set.all()
        if reviews:
            result = self.review_set.all().aggregate(average=Avg('star_count')).get('average')
        else:
            return 0
        return result

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='products/product-images/', format='JPEG', options={'quality': 60})
    order = models.IntegerField(validators=[MinValueValidator(1)])

    @display(description='Mehsulun Movcud Sekilleri')
    def product_image(self):
        return format_html(f'<img width=250 src="{self.image.url}">')
    
    class Meta:
        ordering = ['order']
        verbose_name = "Məhsul Şəkili"
        verbose_name_plural = "Məhsul Şəkililləri"
    

class Review(models.Model):
    customer = models.ForeignKey('customer.Customer', on_delete=models.CASCADE, validators=[MaxValueValidator(5), MinValueValidator(1)])
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    star_count = models.IntegerField()
    comment = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

MultiShop/templates/home.html
{% extends 'layout/layout.html' %}
{% load static %}
{% load i18n %}


{% block title %}
<title>{% trans "Ana Səhifə - MultiShop Axtardığınız hərşeyi tək adrestə tapın!" %}</title>

{% endblock title %}


{% block metas %}
<meta name="keywords" content="alis veris sayti, paltarlar, online alis veris, en ucuz, en keyfiyyetli">      
<meta name="robots" content="index, follow"> 
<meta name="description" content="Axtardiginiz her nov paltarlari burdan tapa bilersiniz, cattirilma mumkundur. toptan qiym,etine perakende satis."> 
<meta property="og:title" content="Ana Səhifə - MultiShop Axtardığınız hərşeyi tək adrestə tapın!"> 
<meta property="og:description" 
  content="Axtardığınız hərşeyi bu adrestə tapa bilərsiniz!" />
<meta property="og:type" content="website"> 
<meta property="og:url" content="{{request.build_absolute_uri}}"> 
<meta property="og:image" content="{% static 'img/multishop.avif' %}">     
<meta property="og:site_name" content="MULTISHOP" />
{% endblock metas %}


{% block main %}
<!-- Carousel Start -->
    <div class="container-fluid mb-3">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for slide in slide_campaings %}
                        <li data-target="#header-carousel" data-slide-to="{{forloop.counter0}}" {% if forloop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for slide in slide_campaings %}
                            <div class="carousel-item position-relative {% if forloop.first %}active{% endif %}" style="height: 430px;">
                                <img class="position-absolute w-100 h-100"   src="{{slide.image.url}}" style="object-fit: cover;">
                                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                    <div class="p-3" style="max-width: 700px;">
                                        <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">{{slide.title}}</h1>
                                        <p class="mx-md-5 px-5 animate__animated animate__bounceIn">{{slide.description}}</p>
                                        <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">{% trans "Categories" %}</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                {% for campaing in campaings|slice:':2' %}
                    <div class="product-offer mb-30" style="height: 200px;">
                        <img class="img-fluid"   src="{{campaing.image.url}}" alt="">
                        <div class="offer-text">
                            <h6 class="text-white text-uppercase">{% trans "Save" %} {{campaing.discount|floatformat}}%</h6>
                            <h3 class="text-white mb-3">{{campaing.title}}</h3>
                            <a href="" class="btn btn-primary">{% trans "Shop Now" %}</a>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- Carousel End -->


    <!-- Featured Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">{% trans "Quality Product" %}</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                    <h5 class="font-weight-semi-bold m-0">{% trans "Free Shipping" %}</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">{% trans "14-Day Return" %}</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">{% trans "24/7 Support" %}</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Featured End -->


    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">{% trans "Categories" %}</span></h2>
        <div class="row px-xl-5 pb-3">
            {% for category in categories %}
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <a class="text-decoration-none" href="">
                        <div class="cat-item d-flex align-items-center mb-4">
                            <div class="overflow-hidden" style="width: 100px; height: 100px;">
                                <img class="img-fluid cat_img"   src="{{category.image.url}}" alt="">
                            </div>
                            <div class="flex-fill pl-3">
                                <h6>{{category.title}}</h6>
                                <small class="text-body">{{category.product_set.count}} Products</small>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
    <!-- Categories End -->


    <!-- Featured Products Start -->
    <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">{% trans "Featured Products" %}</span></h2>
        <div class="row px-xl-5">
            {% for product in featured_products %}
                {% include 'includes/one_product.html' %}
            
            {% endfor %}



        </div>
    </div>
    <!-- Featured Products End -->


    <!-- Offer Start -->
    <div class="container-fluid pt-5 pb-3">
        <div class="row px-xl-5">
            {% for campaing in campaings|slice:"2:" %}
                <div class="col-md-6">
                    <div class="product-offer mb-30" style="height: 300px;">
                        <img class="img-fluid"   src="{{campaing.image.url}}" alt="">
                        <div class="offer-text">
                            <h6 class="text-white text-uppercase">{% trans "Save" %} {{campaing.discount|floatformat}}%</h6>
                            <h3 class="text-white mb-3">{{campaing.title}}</h3>
                            <a href="" class="btn btn-primary">{% trans "Shop Now" %}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <!-- Offer End -->


    <!-- Recent Products Start -->
    <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">{% trans "Recent Products" %}</span></h2>
        <div class="row px-xl-5">
            {% for product in recent_products %}
                {% include 'includes/one_product.html' with product=product %}
            {% endfor %}

        </div>
    </div>
    <!-- Recent Products End -->


    <!-- Vendor Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel vendor-carousel">
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-1.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-2.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-3.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-4.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-5.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-6.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-7.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img   src="{% static 'img/vendor-8.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Vendor End -->
{% endblock main %}

MultiShop/templates/product.html
{% extends 'layout/layout.html' %}
{% load static %}
{% load urlhelper %}
{% load  %}
{% load producthelper %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'ecommerce/product-list/product-list.css' %}">
{% endblock styles %}

{% block main %}
{% url 'ecommerce:product-list' as link %}

{% include 'includes/banner.html' with title1='Products' title2='Product List' link=link %}


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <style>
                .filter-parent {
                    position: relative;
                }
                
                .filter-button {
                width: 80%;
                text-align: center;
                padding: 10px 20px;
                margin: auto;
                background-color:#FFD333 ;
                color: #3D464C;
                font-weight: bold;
                position: sticky;
                bottom: 20px;
                z-index: 2;
                opacity: 0.7;
                
                }
                .filter-button:hover {
                    opacity: 1;
                }
                .filter-button:active {
                    background-color: #FFC801;

                }


            </style>
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4 filter-parent">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span></h5>
                <div class="bg-light p-4 mb-30">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                              <label for="min-price">Min Price</label>
                              <input type="text" class="form-control" id="min-price" limitvalue="{{price_info.min_value|floatformat}}" \
                              placeholder="{{price_info.min_value|floatformat}} currency">
                            </div>
                            <div class="form-group col-md-6">
                              <label for="max-price ">Max Price</label>
                              <input type="text" class="form-control" id="max-price" limitvalue="{{price_info.max_value|floatformat}}" \
                              placeholder="{{price_info.max_value|floatformat}} currency">
                            </div>
                          </div>
                    </form>
                </div>
                <!-- Price End -->
                
                <!-- Color Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span></h5>
                <div class="bg-light p-4 mb-30">
                    <form>
                        {% csrf_token %}
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" class="custom-control-input" id="color-all">
                            <label class="custom-control-label" for="color-all">All Color</label>
                        </div>
                        {% for color in colors %}
                            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                                <input type="checkbox" class="custom-control-input color-input" title-data={{color.title}} id="color-{{color.title}}">
                                <label class="custom-control-label " for="color-{{color.title}}">{{color.title|lower|capfirst}}</label>
                                <span class="badge border font-weight-normal">{{color.count}}</span>
                            </div>
                        {% endfor %}

                    </form>
                </div>
                <!-- Color End -->

                <!-- Size Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span></h5>
                <div class="bg-light p-4 mb-30">
                    <form>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" class="custom-control-input" checked id="size-all">
                            <label class="custom-control-label" for="size-all">All Size</label>
                        </div>
                        {% for size in sizes %}
                            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                                <input type="checkbox" class="custom-control-input size-input" title-data={{size.title}} id="size-{{size.title}}">
                                <label class="custom-control-label" for="size-{{size.title}}">{{size.title}}</label>
                                <span class="badge border font-weight-normal">{{size.count}}</span>
                            </div>
                        {% endfor %}

                    </form>
                    
                </div>
                <div class="filter-button">Apply</div>
                <!-- Size End -->
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start --> 
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Sorting</button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="?{% edit_query request sorting='-created' %}">Latest</a>
                                        <a class="dropdown-item" href="?{% edit_query request sorting='-new_price' %}">First Expensive</a>
                                        <a class="dropdown-item" href="?{% edit_query request sorting='new_price' %}">First Cheap</a>
                                        <a class="dropdown-item" href="?{% edit_query request sorting='-avg_review' %}">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Showing</button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="?{% edit_query request page_by=8 %}">8</a>
                                        <a class="dropdown-item" href="?{% edit_query request page_by=12 %}">12</a>
                                        <a class="dropdown-item" href="?{% edit_query request page_by=16 %}">16</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for product in products %}
                    {% include 'includes/one_product.html'%}
                    {% endfor %}
                    <div class="col-12">
                        <nav>
                            <ul class="pagination justify-content-center">
                                {% if page.has_previous %}
                                    <li class="page-item"><a href="?{% edit_query request page=page.previous_page_number %}" class="page-link">Previous</a></li>
                                {% else %}
                                 <li class="page-item disabled"><a href="" class="page-link">Previous</a></li>
                                {% endif %}
                                
                                {% for page_number in paginator.page_range %}

                                {% if page_number == page.number %}
                                    <li class="page-item active"><a href="?{% edit_query request page=page_number %}" class="page-link">{{page_number}}</a></li>
                                {% else %}
                                    <li class="page-item"><a href="?{% edit_query request page=page_number %}" class="page-link">{{page_number}}</a></li>
                                {% endif %}

                                {% endfor %}

                                {% if page.has_next %}
                                    <li class="page-item"><a href="?{% edit_query request page=page.next_page_number %}" class="page-link">Next</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a href="#" class="page-link">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>



                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->

{% endblock main %}

{% block scripts %}
    <script src='{% static 'ecommerce/product-list/product-list.js' %}'></script>
{% endblock scripts %}