MultiShop/MultiShop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, ProductSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
    'products': ProductSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    #path('robots.txt/', lambda request: render(request, 'robots.txt', content_type='text/plain')), | alttaki setirnen eyni islevi gorur.
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap')
] + i18n_patterns(
    path('', include('ecommerce.urls')),
    path('customer/', include('customer.urls'))
)

MultiShop/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('bascet/', views.bascet, name='bascet'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('confirm-contact/', views.confirm_contact, name='confirm-contact'),
    path('add-to-bascet/<int:pk>/', views.add_to_bascet, name = 'add-to-bascet'),
    path('update-bascet-quantity/<int:pk>/', views.update_bascet_quantity, name = 'update-bascet-quantity'),
    path('remove-bascet/<int:pk>/', views.remove_bascet, name='remove-bascet'),
    path('add-to-wish/<int:pk>/', views.add_to_wish, name = 'add-to-wish'),
    path('remove-wish/<int:pk>/', views.remove_wish, name='remove-wish'),
    path('change-currency/<str:currency>/', views.change_currency, name='change-currency'),
    path('reset-password<str:uuid>/<str:token>', views.reset_password, name='reset-password'),
    path('reset-password-email', views.reset_password_email, name='reset-password-email'),


]

MultiShop/customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from.forms import (
    RegisterForm, ContactForm, CheckoutForm, ResetPasswordEmailForm, ResetPasswordForm
    )
from django.contrib.auth import login, logout, authenticate
from .models import (
    Contact, Customer, Wishlist, BascetItem, Order, Coupon, PasswordReset
    )
from ecommerce.models import Product
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum
from django.views.generic import TemplateView, View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
import os
# Create your views here.

RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')

class ContactView(View):
    def get(self, request):
        form = ContactForm()
        return render(request, 'contact.html', context={'form': form})
    
    def post(self, request):
        form = ContactForm(data=request.POST)
        response = requests.post('https://www.google.com/recaptcha/api/siteverify', {
            'secret': RECAPTCHA_SECRET_KEY,
            'response': request.POST.get('g-recaptcha-response')
        })
        recaptcha_respose = response.json()
        success = recaptcha_respose.get('success')
        score = recaptcha_respose.get('score')
        if form.is_valid() and success and score > 0.7:
            form.save()
            return render(request, 'contact.html', context={'form': ContactForm(), 'status': 'success'})
        return render(request, 'contact.html', context={'form': form, 'status': 'fail'})


def confirm_contact(request):
    if request.method == 'GET':
        return redirect('customer:contact')
    elif request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()
        return redirect('customer:contact')
    
def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
         username = request.POST.get('username')
         password  = request.POST.get('password')
         remember_me = request.POST.get('remember_me')
         user = authenticate(username=username, password=password)
         if user:
             login(request, user)
             nextUrl = request.GET.get('next')
             if not remember_me:
                 request.session.set_expiry(0)
             return redirect(nextUrl or 'ecommerce:home')
         else:
            return render(request, 'login.html', context={'unsuccess': True })
            
def logout_view(request):
    logout(request)
    return redirect('customer:login') 

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'register.html', context={'form': form})

    elif request.method == 'POST':
        form = RegisterForm(data=request.POST)
        accepted = request.POST.get('accepted')
        if form.is_valid() and accepted:
            user = form.save()
            login(request, user)
            return redirect('ecommerce:home')
        elif not accepted:
            return render(request, 'register.html', context={'form': form, 'not_accepted': True})
        else:
            return render(request, 'register.html', context={'form': form})
            
def profile(request):
    if request.method == 'GET':
        form = RegisterForm(data=request.POST)
        return render(request, 'profile.html', context={'form': form})
    elif request.method == 'POST':
        pass
            
  


class WishlistView(LoginRequiredMixin, ListView):
    context_object_name = 'wishlist'
    template_name = 'wishlist.html'
    def get_queryset(self):
        customer = self.request.user.customer
        return customer.wishlist_set.all()
    
      
@login_required
def add_to_wish(requset, pk):

    customer = requset.user.customer
    product = Product.objects.get(pk=pk)
    current_wish = Wishlist.objects.filter(customer=customer,product=product)
    if current_wish:
        current_wish.delete()
    else:
        Wishlist.objects.create(customer=customer, product=product)
    next_url = requset.GET.get('next')
    return redirect(next_url)

@login_required
def remove_wish(request, pk):
    wish = get_object_or_404(Wishlist, pk=pk)
    wish.delete()
    return redirect('customer:wishlist')


@login_required
def bascet(request):
    coupon_code = request.GET.get('coupon_code')
    coupon = Coupon.objects.filter(code=coupon_code).first()
    customer = request.user.customer
    bascet = customer.bascetitem_set.all()
    bascet = bascet.annotate(total_price=F('product__new_price') * F('quantity'))
    total_bascet_price = bascet.aggregate(total_bascet_price=Sum('total_price')).get('total_bascet_price') or 0
    if total_bascet_price == 0:
        shipping_price =0
    elif total_bascet_price <= 30:
        shipping_price = 5
    elif 30 < total_bascet_price <= 120:
        shipping_price = total_bascet_price * 0.165
    else:
        shipping_price = 20
    old_shipping_price = shipping_price
    shipping_free = False
    if total_bascet_price >= 200:
        shipping_free = True
        shipping_price = 0
    total_price = total_bascet_price + shipping_price
    coupon_discount = None
    total_price_with_coupon = None
    if coupon:
        coupon_discount = total_bascet_price * coupon.discount_percent / 100
        total_price_with_coupon = total_price - coupon_discount
        
    context = {
        'bascet': bascet,
        'total_bascet_price': total_bascet_price,
        'coupon': coupon,
        'coupon_discount': coupon_discount,
        'total_price_with_coupon': total_price_with_coupon,
        'invalid_coupon': bool(coupon_code and (not coupon or not coupon.is_valid(customer))),
        'coupon_code': coupon_code,
        'coupon_is_vaild': coupon and coupon.is_valid(customer),
        'shipping_price': shipping_price,
        'shipping_free': shipping_free,
        'total_price': total_price,
        'old_shipping_price': old_shipping_price
        # coupon_code false olsa kupon invaliddir, True olsa: bu adda kupon varsa sistemde coupon True olur ve not coupon = False olur. not coupon False olsa invalid coupon False olur ve kpon do
    }    
    
    return render(request, 'bascet.html', context=context)

@login_required
def add_to_bascet(request,pk):
    if request.method == 'POST':
        customer = request.user.customer
        product = get_object_or_404(Product, pk=pk)
        size = request.POST.get('size')
        color = request.POST.get('color')
        quantity = request.POST.get('quantity')
        BascetItem.objects.create(
            customer=customer, product=product, size_id=size, color_id=color, quantity=quantity
        )
        nexturl = request.POST.get('next')
        return redirect(nexturl or 'customer:bascet')
    else:
        return redirect('ecommerce:home')

@login_required
def remove_bascet(request, pk):
    bascetitem = get_object_or_404(BascetItem, pk=pk)
    bascetitem.delete()
    return redirect('customer:bascet')

@login_required
def update_bascet_quantity(request, pk):
    quantity = request.POST.get('quantity')
    bascet = get_object_or_404(BascetItem, pk=pk)
    bascet.quantity = quantity
    bascet.save()
    return redirect('customer:bascet')


def checkout(request):
    user = request.user
    coupon_code = request.GET.get('coupon_code')
    coupon = Coupon.objects.filter(code=coupon_code).first()
    customer = request.user.customer
    bascet = customer.bascetitem_set.all()
    bascet = bascet.annotate(total_price=F('product__new_price') * F('quantity'))
    total_bascet_price = bascet.aggregate(total_bascet_price=Sum('total_price')).get('total_bascet_price') or 0
    if total_bascet_price == 0:
        shipping_price =0
    elif total_bascet_price <= 30:
        shipping_price = 5
    elif 30 < total_bascet_price <= 120:
        shipping_price = total_bascet_price * 0.165
    else:
        shipping_price = 20
    old_shipping_price = shipping_price
    shipping_free = False
    if total_bascet_price >= 200:
        shipping_free = True
        shipping_price = 0
    total_price = total_bascet_price + shipping_price
    coupon_discount = None
    total_price_with_coupon = None
    if coupon:
        coupon_discount = total_bascet_price * coupon.discount_percent / 100
        total_price_with_coupon = total_price - coupon_discount

    coupon_is_valid = coupon and coupon.is_valid(customer)
        
    form = CheckoutForm(initial={'first_name': user.first_name, 'last_name': user.last_name, 'email': user.email})
    saved_money = float(old_shipping_price) + float(coupon_discount if coupon_discount != None else 0)
    context = {
    'form': form,
    'bascet': bascet,
    'coupon_code': coupon_code,
    'total_price': total_price,
    'total_bascet_price': total_bascet_price,
    'shipping_price': shipping_price,
    'total_price_with_coupon': total_price_with_coupon,
    'coupon_discount': coupon_discount,
    'old_shipping_price': old_shipping_price,
    'saved_money': saved_money,
    }
    if request.method == 'GET':
        return render(request, 'checkout.html', context=context)
    elif request.method == 'POST':
        form = CheckoutForm(data=request.POST)
        if form.is_valid():
            order = form.save(request.user.customer, coupon, coupon_is_valid, total_price, total_price_with_coupon)
            return redirect('ecommerce:home')
        # email = request.POST.get('email')
        # phone = request.POST.get('phone')
        # last_name = request.POST.get('last_name')
        # first_name = request.POST.get('first_name')
        # address = request.POST.get('address')
        # district = request.POST.get('district')
        # city = request.POST.get('city')

MultiShop/customer/templates/bascet.html
{% extends 'layout/layout.html' %}
{% load static %}
{% block main %}
{% url 'customer:backet' as link %}

{% include 'includes/banner.html' with title1='Products' title2='Backet' link=link %}



    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th></th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for bascetitem in bascet %}
                            <tr>
                                <td class="align-middle"><a class="text-decoration-none black font-weight-bold text-capitalize text-dark" href="{{ bascetitemproduct.get_absolute_url}}"><img class="pr-2" src="{{bascetitem.product.cover.url}}" alt="" style="width: 50px;"></a></td>
                                <td class="align-middle"><a class="text-decoration-none black font-weight-bold text-capitalize text-dark" href="{{ bascetitem.product.get_absolute_url}}"> {{bascetitem.product.title}}</a></td>
                                <td class="align-middle">{{bascetitem.color}}</td>
                                <td class="align-middle">{{bascetitem.size}}</td>
                                <td class="align-middle">{{bascetitem.product.new_price|floatformat:2}} AZN</td>
                                <td class="align-middle">
                                    <form action="{% url 'customer:update-bascet-quantity' pk=bascetitem.pk %}" method="POST">
                                        {% csrf_token %}
                                        <div class="input-group quantity mx-auto" style="width: 100px;">
                                            <div class="input-group-btn">
                                                <button class="btn btn-sm btn-primary btn-minus" >
                                                <i class="fa fa-minus"></i>
                                                </button>
                                            </div>
                                            <input type="text" name="quantity" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{bascetitem.quantity}}">
                                            <div class="input-group-btn">
                                                <button class="btn btn-sm btn-primary btn-plus">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                                <td class="align-middle">{{bascetitem.total_price|floatformat:2}} AZN</td>
                                <td class="align-middle"><a href="{% url 'customer:remove-bascet' pk=bascetitem.pk%}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="" method="GET">
                    <div class="input-group">
                        <input type="text" name="coupon_code" class="form-control border-0 p-4 
                        {% if invalid_coupon %}text-danger{% elif coupon_is_vaild %}text-success{% endif %}" placeholder="Coupon Code" value="{% if coupon_code %}{{coupon_code}}{% endif %}">

                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>

                    {% if invalid_coupon %}
                        <span class="text-danger font-weight-bold">Invalid Coupon</span>
                    {% endif %}
                    {% if coupon_is_vaild %}
                    <span class="text-success font-weight-bold">{{coupon.discount_percent|floatformat}}% DISCOUNT APPLIED</span>
                    {% endif %}
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>{{total_bascet_price|floatformat:2}} AZN</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium ">Shipping</h6>
                            <h6 class="font-weight-medium" style="{% if shipping_price != old_shipping_price %}text-decoration: line-through; font-size: small;{% endif %}">{{old_shipping_price|floatformat:2}} AZN</h6>
                        </div>
                        {% if coupon_is_vaild %}
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium ">Coupon Discount</h6>
                                <h6 class="font-weight-medium" style="text-decoration: line-through; font-size: small;">{{coupon_discount|floatformat:2}} AZN</h6>
                            </div>
                        {% endif %}
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            {% if coupon_is_vaild %}
                                <h5>{{total_price_with_coupon|floatformat:2}} AZN</h5>
                            {% else %}
                                <h5>{{total_price|floatformat:2}} AZN</h5>
                            {% endif %}
                        </div>
                        {% if coupon_is_vaild %}
                            <a href="{% url 'customer:checkout' %}?coupon_code={{coupon_code}}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                        {% else %}
                            <a href="{% url 'customer:checkout' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->


{% endblock main %}

MultiShop/customer/templates/checkout.html
{% extends 'layout/layout.html' %}
{% load static %}
{% block main %}
{% url 'customer:checkout' as link %}

{% include 'includes/banner.html' with title1='Products' title2='Checkout' link=product_list %}


    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Billing Address</span></h5>
                <div class="bg-light p-30 mb-5">
                    <form id="checkout-form" class="row" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="col-md-6 form-group mt-2">
                                <label>{{field.label}}</label>
                                {{field}}
                                {% for error in field.errors %}
                                    <small class="text-danger">{{error}}</small>
                                {% endfor %}
                            </div> 
                        {% endfor %}  
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom">
                        <h6 class="mb-3">Products</h6>
                        {% for bcitem in bascet %}
                            <div class="d-flex justify-content-between">
                                <p>{{bcitem.product.title}} <span class="small">( {{bcitem.color}}-{{bcitem.size}} )</span></p>
                                <p>{{bcitem.product.new_price|floatformat:2}} AZN x {{bcitem.quantity}}</p>
                            </div>
                        {% endfor %}

                    </div>
                    <div class="border-bottom pt-3 pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>{{total_bascet_price|floatformat:2}} AZN</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium ">Shipping</h6>
                            <h6 class="font-weight-medium" style="{% if shipping_price != old_shipping_price %}text-decoration: line-through; font-size: small;{% endif %}">{{old_shipping_price|floatformat:2}} AZN</h6>
                            {% comment %} <h6 class="font-weight-medium">{{shipping_price|floatformat:2}} AZN</h6> {% endcomment %}
                        </div>
                        {% if coupon_code %}
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium ">Coupon Discount</h6>
                                <h6 class="font-weight-medium" style="text-decoration: line-through; font-size: small;">{{coupon_discount|floatformat:2}} AZN</h6>
                            </div>
                        {% endif %}
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            {% if coupon_code %}
                                <h5>{{total_price_with_coupon|floatformat:2}} AZN</h5>
                            {% else %}
                                <h5>{{total_price|floatformat:2}} AZN</h5>
                            {% endif %}
                        </div>
                        <div class="d-flex justify-content-between mt-2" >
                            <h6 style="color: #28a745;">You Saved</h6>
                            <h6 style="color: #28a745;">{{saved_money|floatformat:2}} AZN</h6>
                        </div>
                    </div>
                    <button onclick="document.getElementById('checkout-form').submit()" class="btn btn-block btn-primary font-weight-bold py-3 mt-4">Place Order</button>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Checkout End -->



{% endblock main %}

MultiShop/customer/templates/login.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block main %}
{% url 'customer:login' as link %}
{% include 'includes/banner.html' with title1='User_name' title2='Login' link=product_list %}

    <div class="row justify-content-center">
        <div class="col-5 bg-primary p-3">
            <div class="pt-5">  
                <div class="global-container">  
                <div class="card login-form">  
                <div class="card-body">

                    {% if unsuccess %}
                         <div class="alert alert-danger " role="alert">Istifadeci adi veya sifre xetalidir!</div>
                    {% endif %}

                    {% if email_send %}
                        <div class="alert alert-success " role="alert">Şifrə sıfırlama keçid linki mail adresinizə uğurla göndərildi!</div>
                    {% endif %}

                    {% if password_changed %}
                        <div class="alert alert-success " role="alert">Şifrəniz uğurla dəyişdirildi!</div>
                   {% endif %}

                    <div class="card-text">
                        <form method='POST'>
                            {% csrf_token %}  
                            <div class="form-group">  
                                 <label for="exampleInputUsername1"> Istifadeci Adi </label>  
                                <input type="username" class="form-control form-control-sm" id="exampleInputusername1" name='username'>  
                            </div>  
                            <div class="form-group">  
                                <label for="exampleInputPassword1"> Password </label>  
                                <a href="{% url 'customer:reset-password-email' %}" class="sign-up" style="float:right"> Forgot password? </a>  
                                <input type="password" class="form-control form-control-sm" id="exampleInputPassword1" name='password'>  

                            </div>  
                            <button type="submit" class="btn btn-primary btn-block"> Sign in </button>  
                                
                            <div class="sign-up pt-3">  
                                Don't have an account? <a href="{% url 'customer:register' %}"> Create One </a>  
                                <span style="float:right;" class="sign-up">
                                    <input type="checkbox"  class="form-check-input" id="exampleCheck1" name="remember_me">
                                    <label for="exampleCheck1" class="form-check-label" ><a href="#" >Remember Me</a></label>
                                </span>
                            </div>  
                        </form>  
                    </div>  
                </div>  
            </div>  

            </div>  
        </div>
    </div>

{% endblock main %}

MultiShop/customer/templates/register.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block main %}
{% url 'customer:register' as link %}

{% include 'includes/banner.html' with title1='User_name' title2='Register' link=product_list %}

    <div class="row justify-content-center">
        <div class="col-5 bg-primary p-3">
            <div class="pt-5">  
                <div class="global-container">  
                <div class="card login-form">  
                <div class="card-body">
                    <div class="card-text">
                        <div>
                            {% for error in form.non_field_errors %}
                            <small class="text-danger">{{error}}</small>
                            {% endfor %}
                        </div>
                        <form method='POST'>  
                            {% csrf_token %}
                            <div class="form-group">
                                {% for field in form %}
                                    <label for="{{form.subject.id_for_label }}">{{field.label}}</label>  
                                    {% comment %} <input type="text" class="form-control form-control-sm" id="exampleInputName1">   {% endcomment %}
                                    {{field}}
                                    <div>
                                        {% for error in field.errors %}
                                        <small class="text-danger">{{error}}</small>
                                        {% endfor %}
                                    </div>
                                
                                {% endfor %}
                            </div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1" name="accepted">
                                <label for="exampleCheck1" class="form-check-label" ><a href="#" >Accept Terms and Conditions</a></label>
                                {% if not_accepted %}
                                    <div><small class="text-danger">Sertler qebul edilmelidir!</small></div>
                                {% endif %}
                            </div>
                            <button type="submit" class="btn btn-primary btn-block"> Sign up </button>  
 
                        </form>  
                    </div>  
                </div>  
            </div>  

            </div>  
        </div>
    </div>

{% endblock main %}

MultiShop/customer/templates/wishlist.html
{% extends 'layout/layout.html' %}
{% load static %}
{% block main %}
{% url 'customer:wishlist' as link %}

{% include 'includes/banner.html' with title1='Products' title2='Wishlist' link=product_list %}



    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-12 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th></th>
                            <th>Price</th>
                            <th>Add To Card</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for wish in wishlist %}
                            <tr>
                                <td class="align-middle"><a class="text-decoration-none black font-weight-bold text-capitalize text-dark" href="{{ wish.product.get_absolute_url}}"><img src="{{wish.product.cover.url}}" alt="" style="width: 50px;"></a></td>
                                <td class="align-middle"><a class="text-decoration-none black font-weight-bold text-capitalize text-dark" href="{{ wish.product.get_absolute_url}}"> {{wish.product.title}}</a></td>
                                <td class="align-middle">{{wish.product.new_price|floatformat:2}} AZN <br><small><del>{{wish.product.old_price|floatformat:2}} AZN</del></small></td>
                                <td class="align-middle"><a href="{{ wish.product.get_absolute_url}}" class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></button></a></td>
                                <td class="align-middle"><a href="{% url 'customer:remove-wish' pk=wish.pk%}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                            </tr>
                        {% endfor %}
                   
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Cart End -->


{% endblock main %}