MultiShop/MultiShop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, ProductSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
    'products': ProductSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    #path('robots.txt/', lambda request: render(request, 'robots.txt', content_type='text/plain')), | alttaki setirnen eyni islevi gorur.
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap')
] + i18n_patterns(
    path('', include('ecommerce.urls')),
    path('customer/', include('customer.urls'))
)

MultiShop/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('bascet/', views.bascet, name='bascet'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('confirm-contact/', views.confirm_contact, name='confirm-contact'),
    path('add-to-bascet/<int:pk>/', views.add_to_bascet, name = 'add-to-bascet'),
    path('update-bascet-quantity/<int:pk>/', views.update_bascet_quantity, name = 'update-bascet-quantity'),
    path('remove-bascet/<int:pk>/', views.remove_bascet, name='remove-bascet'),
    path('add-to-wish/<int:pk>/', views.add_to_wish, name = 'add-to-wish'),
    path('remove-wish/<int:pk>/', views.remove_wish, name='remove-wish'),
    path('change-currency/<str:currency>/', views.change_currency, name='change-currency'),
    path('reset-password<str:uuid>/<str:token>', views.reset_password, name='reset-password'),
    path('reset-password-email', views.reset_password_email, name='reset-password-email'),


]

MultiShop/ecommerce/urls.py
from django.urls import path
from . import views


app_name = 'ecommerce'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('detail/product/<int:pk>/<str:slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('review/<int:pk>/', views.review, name='review')
]

MultiShop/templates/includes/banner.html
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="{% url 'ecommerce:home' %}">Home</a>
                <a class="breadcrumb-item text-dark" href="{{link}}">{{title1}}</a>
                <span class="breadcrumb-item active">{{title2}}</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

MultiShop/templates/includes/one_product.html
{% load generalinfo %}
{% load producthelper %}
<div class="col-lg-3 col-md-4 col-sm-6 pb-1">
    <div class="product-item bg-light mb-4">
        <div class="product-img position-relative overflow-hidden">
            <img class="img-fluid one_pr_img"   src="{{product.cover.url}}" alt="">
            <div class="product-action">
                <a class="btn btn-outline-dark btn-square" href="{{ product.get_absolute_url}}"><i class="fa fa-search"></i></a>
                <a class="btn btn-outline-dark btn-square" href="{% url 'customer:add-to-wish' pk=product.pk%}?next={{request.get_full_path }}"><i class="{% if product|is_wished:request %}fas fa-heart text-primary{% else %}far fa-heart{% endif %}"></i></a>
            </div>
        </div>
        <div class="text-center py-4">
            <a class="h6 text-decoration-none text-truncate" href="">{{product.title}}</a>
            <div class="d-flex align-items-center justify-content-center mt-2">
                {% if product.old_price %}
                    <h5></h5><h6 class="text-muted ml-2"><del>{% price_text request product.old_price %}</del></h6>
                {% else %}
                    <h5>{% price_text request product.new_price %}</h5>
                {% endif %}
            </div>
            <div class="d-flex align-items-center justify-content-center mb-1">
                {% comment %} <small class="fa fa-star text-primary mr-1"></small> {% endcomment %}
                {% stars product.average_star_count %}
                <small>({{product.review_set.count}})</small>
            </div>
        </div>
    </div>
</div>

MultiShop/templates/includes/stars.html
<span class="stars">
    {% for f in full %}
        <i class="fas fa-star text-primary mr-1"></i>
    {% endfor %}
    {% for h in half %}
        <i class="fas fa-star-half-all text-primary mr-1"></i>
    {% endfor %}
    {% for e in empty %}
        <i class="far fa-star text-primary mr-1"></i>
    {% endfor %}
</span>